# version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: 
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: backend
    restart: always
    working_dir: /app
    env_file: ./.env
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - postgres
      - redis
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
  
  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data
    restart: unless-stopped
  
  worker:
    build:
      context: ./worker
      dockerfile: ../docker/worker.Dockerfile
    container_name: worker
    env_file: ./.env
    volumes:
    - ./worker:/app
    - worker_node_modules:/app/node_modules
    depends_on:
      - backend
      - redis
  
  bull-board:
    image: 'venatum/bull-board:latest'
    container_name: mediaforge-bullboard
    ports:
    - "5000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      USER_LOGIN: admin
      USER_PASSWORD: bullpass
    depends_on:
      - redis

volumes:
  redis_data:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
  worker_node_modules:
