# version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    container_name: backend
    restart: always
    working_dir: /app
    env_file: ./.env
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - postgres
  
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
  
  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data
    restart: unless-stopped


volumes:
  redis_data:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
